name: A Single Click
favicon: null
layout_spectrum: 0.30778156756423414
typography_spectrum: 0.8949927904177457
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2200582472141832
  lightness: 0.16833484661765397
  saturation: 0.7672796894330531
  rhythmicContrast: 0.4255333507899195
purpose: []
